### ISSUE TITLE
PULL_REQUEST_{TO,FROM}_{HTTP,SSH}_CLONE_URL variables contains username

### ISSUE THREAD

**Issue by johntconklin** [tomasbjerre/pull-request-notifier-for-bitbucket#229]
I've found that using the PULL_REQUEST_{TO,FROM}_{HTTP,SSH}_CLONE_URL variables inconvenient to use as is, because of the username in the URL.  My agents that use the URL don't use that username (and could not, because it doesn't have the password for that username).  I don't know whether there is a use case where the username is useful, in which case, the username could be removed.  But if there is a use case, please consider adding another set of _URL variables that don't include username.

**Comment by tomasbjerre** [comment]
@christiangalsterer what do you think about removing the usernames? I'm asking because you introduced it in https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/commit/001a9c7ce0d89b9 .

I would vote for removing it.

**Comment by christiangalsterer** [comment]
Hi,

as long as we keep the variables (we heavily rely on it in our build pipeline) as such and remove only the username from the URL I'm fine with it.

**Comment by tomasbjerre** [comment]
Thanks to @jwoolston and his PR, this is now released in 3.20!

**Comment by jwoolston** [comment]
I really appreciate the speedy release, this will help a lot, thank you.

**Comment by tomasbjerre** [comment]
I'm thinking that the SSH clone URL should still have `git@...`. But the HTTP clone URL should not have username.

What do you say @johntconklin ?

**Comment by steve-behnke-spacex** [comment]
Thank you for considering -- That would be ideal for our use-case.

**Comment by tomasbjerre** [comment]
Fixed in 3.22.

**Comment by steve-behnke-spacex** [comment]
Radical. Thank you @tomasbjerre.

**Comment by johntconklin** [comment]
I'm no longer in an organization that uses Bitbucket, but if I recall correctly the SSH URL's included the name of the user who raised the pull request, not a generic "git@".  So a pull request raised by user "foo" had a URL foo@stash.example.com:/project/PROJ/repo/REPO, and as a result, the build service account used for builds triggered by the event could not use the URL as-is, because it did not have credentials for "foo".  To my mind, the URL and the access credentials are two completely separate things, and as such, the user should not be included in the URL.

@theucke, you may want to follow this.

**Comment by steve-behnke-spacex** [comment]
Ssh URLs have git as the username I assure you.

Respectfully, Steven Behnke

On Jun 8, 2018, at 8:15 AM, J.T. Conklin <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm no longer in an organization that uses Bitbucket, but if I recall correctly the SSH URL's included the name of the user who raised the pull request, not a generic "git@". So a pull request raised by user "foo" had a URL foo@stash.example.com<mailto:foo@stash.example.com>:/project/PROJ/repo/REPO, and as a result, the build service account used for builds triggered by the event could not use the URL as-is, because it did not have credentials for "foo". To my mind, the URL and the access credentials are two completely separate things, and as such, the user should not be included in the URL.

@theucke<https://github.com/theucke>, you may want to follow this.
