### ISSUE TITLE
RESCOPED_FROM should trigger a build for each push

### ISSUE THREAD

**Issue by JavierLight** [tomasbjerre/pull-request-notifier-for-bitbucket#281]
Maybe I'm wrong, but I was expecting this plugin to trigger only one build for each push. When pushing multiple commits, we only care about the last one.

* `RESCOPED_FROM` Event Example 

![image](https://user-images.githubusercontent.com/7041691/38796881-15219ea2-415d-11e8-8932-79feed4e9d4b.png)

* Expected behavior:
Only 1 new build is triggered in Jenkins.

* Actual behavior:
4 builds are triggered in Jenkins.

Thanks for your time.

**Comment by tomasbjerre** [comment]
One notification should only trigger once per push. 

Perhaps you have setup multiple notifications that each trigger once?

**Comment by JavierLight** [comment]
Hi Tomas, thanks for your quick reply.

I've set 2 notifications for this repo pointing to this job, but the triggers are different.

* Notification 1: `BUTTON_TRIGGER`
* Notification 2: `OPENED`, `RESCOPED_FROM`

I created a new PR in my repo to specifically reproduce this behavior. Could it be that the button notification is triggering the job as well?

**Comment by tomasbjerre** [comment]
That would be such a major bug. I think more people would report that if it was an issue.

I would suspect that someone else have added notifications. You may not see them because of your user privilegies.

Would also be interesting to see what information is sent to the triggered job. What event it is.
