### ISSUE TITLE
Obtain crumb from Jenkins 2.176.3

### ISSUE THREAD

**Issue by qibint** [tomasbjerre/pull-request-notifier-for-bitbucket#349]
Hi,
We're facing the following issue when we use the trigger button to build in Jenkins when using the plugin. The bitbucket server logs to print the following as:

**c.s.j.s.c.servlet.WebComponent A servlet request, to the URI https://xxx/rest/prnfb-admin/1.0/settings/buttons/ed0....3f/press/repository/xxx/pullrequest/1, contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.**

Any suggestion?
Thank you

**Comment by qibint** [comment]
After the clicking the trigger build, the response is 
403 https://user_name:api_token@jenkins_url.com/xxxxx/PR-1/build
You may check network tab in web browser for exact URL and response.

But I can use the URL with same username and token to access the Jenkins end point using curl command or directly visiting through a web browser.

**Comment by tomasbjerre** [comment]
Perhaps a proxy server between Bitbucket and Jenkins? It may respond with 403.

**Comment by qibint** [comment]
Yes. We use an AWS ELB in front of the Jenkins server to redirect http traffic to https. Do you think that will be an issue?

**Comment by tomasbjerre** [comment]
Sounds like it. There is a proxy feature in the plugin that may work for you.

**Comment by qibint** [comment]
Thank you Tom for quick response and support.
We finally find the root cause of the issue. Hope can help anyone else here.
For the latest stable version of Jenkins(2.176.3), there is a fix about CSRF protection tokens.
**This fix may impact scripts that obtain a crumb from the crumb issuer API. They may need to be updated to retain the session ID for subsequent requests.** So by using Strict Crumb Issuer Plugin in Jenkins can strict the Jenkins-Crumb values stay the same during a specific time.

refer to:
https://jenkins.io/changelog-stable/
https://jenkins.io/security/advisory/2019-08-28/
https://plugins.jenkins.io/strict-crumb-issuer

**Comment by kentgitbub** [comment]
Think there may be a connection between this issue and the one I wrote #348 since I se.

Having said that I don't think the right way forward is to install yet another plugin since it, in my view, clearly is something that needs attention in the notifier plugin. I'd rather see an updated version that works with Jenkins 2.193 onwards. 

As a consquence, people that install the notifier plugin for the first time on a Jenkins 2.193 will scratch their heads forever without getting it to work so an update is very much appreciated. I have alreay rolled back our Jenkins to the previous version (2.189) and now it works again.

PS.  We DON'T want to live without this otherwise cracking plugin :-) 
-- Kent

**Comment by tomasbjerre** [comment]
I opened #350 to implement session storage. But it is not a priority for me as I am no longer using this plugin. Pull requests are welcome!
