### ISSUE TITLE
In configuration on a save, not saving all info (e.g. checkbox checked).

### ISSUE THREAD

**Issue by carlmot** [tomasbjerre/pull-request-notifier-for-bitbucket#74]
Plugin version 2.5 installed in Bitbucket 4.0.1.  Checked box not saved as checked when checked for 'Button_Trigger', 'Rescoped_From', Rescoped_To'. Other checkboxes save ok.  
Not seeing any unique errors/warnings in browser - see similar for an older 1.17 version of the plugin on Stash 3.11.1. Did not see notice any errors in log file.

**Comment by tomasbjerre** [comment]
Sorry the previous fix was a bit to quick =) Should work now in 2.6!

**Comment by tomasbjerre** [comment]
I created a 1.31 release for users of Stash 3.x. Its available here:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-stash-1.31
I will not upload it to Atlassian Marketplace because that will make the plugin show as only compatible with Stash 3.x... ( https://answers.atlassian.com/questions/30935697/how-do-i-maintain-plugin-compatible-with-stash-3-and-bitbucket-4 )
